# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6cbeb3a8f341afe8c8bb711d7506ae2516a1c122648394480ad6b79b21fb28043e8903a8638b2154ae929b890e2c83fe24eb31fdd30e5a1bce6af8bcd021944

test:
  secret_key_base: abaf120d3b0e3f2f46b44cb34ef0afc726667ea9873508da381ebbf3102cf555fee9e2713bdb3f1d3713c1c562725c3136ad75721a74440ce9c99547b60b6da1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
